spring.application.name=MovieLibrary
spring.datasource.url=jdbc:mariadb://localhost:3306/movie_library
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
omdb.api.url=http://www.omdbapi.com/
omdb.api.key=d6e9ce1d
